list:
    just -l

# gemini:
#     gemini -a folder todo

open-demo01:
    cd ~/git/gemini-cli-demos/demos/sqlite-investigation && code . DEMO_SCRIPT.md

reconcile-readme:
    gemini -y -p 'Fix the README.md based on existing demos under demos/. Ensure all TABLE fields are populated.'
